fix

diff --git a/tests/main_tests b/tests/main_tests
--- a/tests/main_tests
+++ b/tests/main_tests
@@ -16,19 +16,23 @@ FINAL_EXIT_CODE=0
 tmp_db_file="$HOME/db_file"
 
 function run_and_fail {
-	name=$1
-	code=$2
-	wanted_exit_code=$3
+	if [[ $FINAL_EXIT_CODE -eq 0 ]]; then
+		name=$1
+		code=$2
+		wanted_exit_code=$3
 
-	echo -e "${YELLOW}Running $name${NC}"
+		echo -e "${YELLOW}Running $name${NC}"
 
-	eval "$code"
+		eval "$code"
 
-	exit_code=$?
+		exit_code=$?
 
-	if [[ $exit_code -ne $wanted_exit_code ]]; then
-		echo -e "${RED}Failed: $code got $exit_code, wanted exit-code $wanted_exit_code${NC}"
-		FINAL_EXIT_CODE=1
+		if [[ $exit_code -ne $wanted_exit_code ]]; then
+			echo -e "${RED}Failed: $code got $exit_code, wanted exit-code $wanted_exit_code${NC}"
+			FINAL_EXIT_CODE=1
+		fi
+	else
+		echo -e "${YELLOW}Skipping $name because an earlier test has failed${NC}"
 	fi
 }
 
@@ -45,6 +49,8 @@ run_and_fail "Main-script with --help" "bash smartlocate --help" 0
 run_and_fail "Search for cat" "bash smartlocate --dbfile $tmp_db_file cat" 0
 
 run_and_fail "Search for cat" "bash smartlocate --dbfile $tmp_db_file Mittelbach" 0
+
+run_and_fail "Vacuuming" "bash smartlocate --dbfile $tmp_db_file --vacuum" 0
 
 if [[ -e $tmp_db_file ]]; then
 	rm $tmp_db_file
